### ISSUE TITLE
ESLint-related packages migration - TODO

### ISSUE THREAD

**Issue by nicolo-ribaudo** [babel/babel#10709]
- [x] Merge https://github.com/babel/babel/pull/10705
- [x] Remove lock files from new packages (https://github.com/babel/babel/pull/10711)
- [ ] ~~Ignore new packages while linting~~
- [x] Make "Lint" pass on CI (https://github.com/babel/babel/pull/10712)
- [x] Move CHANGELOG files to `.github/` (https://github.com/babel/babel/pull/10714)
- [x] Actually rename the new packages (https://github.com/babel/babel/pull/10715)
- [x] Prevent lerna from publishing those packages until we are ready (@nicolo-ribaudo) (https://github.com/babel/babel/pull/10722)
- [x] Unify build process (https://github.com/babel/babel/pull/10723, https://github.com/babel/babel/pull/10729)
- [x] Migrate from `mocha` to `jest` (which is used by the other `@babel/` packages) (https://github.com/babel/babel/pull/10716)
- [x] Disable tests for ESLint related packages on unsupported node versions (https://github.com/babel/babel/pull/10730)

**Comment by rajasekarm** [comment]
Can I pick this? Migrate from mocha to jest

**Comment by nicolo-ribaudo** [comment]
Ok :+1:

**Comment by nicolo-ribaudo** [comment]
If you wait 5 mins, I will push the linting PR first

**Comment by JLHwung** [comment]
Yep, let's make the CI green again.

**Comment by rajasekarm** [comment]
Sure, I'm making the change. I'm using https://github.com/skovhus/jest-codemods to make the change.

**Comment by kaicataldo** [comment]
Assigning this to myself so I don't lose track of this, but that doesn't mean others should hold off on working on these tasks.

**Comment by kaicataldo** [comment]
Looks like we’re all set except for renaming the packages. Thoughts on how to proceed? I’m of the mind that we should all of this with the next minor released that occurs after the new packages are ready.

**Comment by thiagoarrais** [comment]
Maybe related? https://github.com/babel/babel-eslint/pull/807

@rajasekarm: what do you think?

**Comment by rajasekarm** [comment]
Yeah, This changes should be added here.

**Comment by nicolo-ribaudo** [comment]
Please wait for Kai's go-ahead before opening new features/bug fixes in this repo.

**Comment by rajasekarm** [comment]
Sure
