### ISSUE TITLE
Optional Chaining Bugs Checklist

### ISSUE THREAD

**Issue by jridgewell** [babel/babel#7256]
- [x] Delete on optional chain should work `delete a?.b`: https://github.com/babel/babel/pull/7257
- [x] Optional should be removed from `NewExpression` AST
- [x] Optional `MemberExpressions` need to become a new AST node `OptionalChain`, to fix issues with should-not-parse grammars
- [x] Ensure OptionalChain cannot be the LHS of Assignment/Update expressions, tag of a TaggedTemplateLiteral, have a Super object, nor the callee of a NewExpresion

**Comment by nveenjain** [comment]
I would love to work on this issue if available.

**Comment by jridgewell** [comment]
Hi @nveenjain!

Part 1 is already done.

Part 2/3 are closely intertwined. Unfortunately, they're rather difficult to accomplish. It'll take creating a brand new node type, called `OptionalMemberExpression`, which propogates upwards, and can be broken by a non-optional member or call expression (or a parenthesis, because syntax). It'll also likely break things inside the babel transforms, since they now have to handle a new member syntax.

**Comment by nveenjain** [comment]
Well, if the tasks are difficult, i will try to implement them. Incase I'm not able to, i would surely like to review the PR, to watch out for implementation.

**Comment by nveenjain** [comment]
I was going through proposed spec. Don't we need the name of new node be `OptionalExpression` and it's expression property be one of `MemberExpression` or `CallExpression` and an `OptionalChain` node?

**Comment by jridgewell** [comment]
We can name it whatever. Leaving it `OptionalMemberExpression` will likely be easiest for transforms.

`OptionalChainingPunctuator` is just the `??.` sigil.

**Comment by jridgewell** [comment]
Regarding the `OptionalMemberExpression` AST node, it should be:

```js
interface OptionalMemberExpression <: MemberExpression {
  type: "OptionalMemberExpression";
  object: MemberExpression | CallExpression;
  property: Identifier | Expression;
  computed: boolean;
}
```

**Comment by nveenjain** [comment]
@jridgewell what should be `OptionalChain` AST node Interface?

**Comment by jridgewell** [comment]
That is `OptionalChain`. 😉

Spec names don't matter for us. What it's trying to define is two separate member expressions:

```js
obj?.a
```

Is an `OptionalMemberExpression`, with object `Identifier("obj")`, property `Identifier("a")`, computed `false`, and optional `true`.

If we then add a `.b` to it, we get another `OptionalMemberExpression` (this is the `OptionalChain` thing):

```js
{ // OptionalMemberExpression
  object: { // OptionalMemberExpression
    object: Identifier("obj"),
    property: Identifier("a"),
    computed: false,
    optional: true,
  },
  property: Identifier("b"),
  computed: false,
  optional: false,
}
```

Notice that `.b`'s `optional` is false, even though it is still an `OptionalMemberExpression`. Now, the `object` can be either a `OptionalMemberExpression`, `MemberExpression`, or a `CallExpression`.

Also note that `OptionalMemberExpression` can turn into a regular `MemberExpression` if surrounded by parenthesis (due to syntax grammars):

```js
(obj?.a).b

// ast:
{ // MemberExpression
  object: { // OptionalMemberExpression
    object: Identifier("obj"),
    property: Identifier("a"),
    computed: false,
    optional: true,
  },
  property: Identifier("b"),
  computed: false,
}
```

**Comment by nveenjain** [comment]
Thanks, that cleared a lot of doubts :smiley:

**Comment by jridgewell** [comment]
Ohhh! We might be able to reuse `MemberExpression`!

We can turn `optional` into a tri-state boolean: `true`, `false`, `undefined`.

**Comment by jridgewell** [comment]
With tri-state `optional` field:

```js
obj.a
{ // MemberExpression
  object: Identifier("obj"),
  property: Identifier("a"),
  computed: false,
  optional: undefined,
}

obj.a.b
{ // MemberExpression
  object: { // MemberExpression
    object: Identifier("obj"),
    property: Identifier("a"),
    computed: false,
    optional: undefined,
  },
  property: Identifier("b"),
  computed: false,
  optional: undefined,
}

obj?.a
{ // MemberExpression
  object: Identifier("obj"),
  property: Identifier("a"),
  computed: false,
  optional: true,
}

obj?.a.b
{ // MemberExpression
  object: { // MemberExpression
    object: Identifier("obj"),
    property: Identifier("a"),
    computed: false,
    optional: true,
  },
  property: Identifier("b"),
  computed: false,
  optional: false,
}

obj?.a?.b
{ // MemberExpression
  object: { // MemberExpression
    object: Identifier("obj"),
    property: Identifier("a"),
    computed: false,
    optional: true,
  },
  property: Identifier("b"),
  computed: false,
  optional: true,
}

(obj?.a).b
{ // MemberExpression
  object: { // MemberExpression
    object: Identifier("obj"),
    property: Identifier("a"),
    computed: false,
    optional: true,
  },
  property: Identifier("b"),
  computed: false,
  optional: undefined,
}
```

**Comment by loganfsmyth** [comment]
I'm having trouble wrapping my head around the idea of a tristate here. Personally that seems super likely to confuse others too. From the standpoint of breaking transforms, isn't this going to break things either way since nothing knows to expect a tri-state flag either?

**Comment by nveenjain** [comment]
@loganfsmyth, according to me no transform breaks when implemented using tristate for `optional`. As current transforms are not using optional(except optionalChaining ones) and those who don't require it will have value `undefined` received as optional property. So that test case would behave exactly the same as not having `optional` property. Looking for other's point of view though.

**Comment by loganfsmyth** [comment]
I guess it depends what we mean by breaking. If a plugin transforms `MemberExpression` nodes and doesn't know to expect `optional` as a flag, won't that plugin transform the code in such a way that the code is broken?, e.g.

```
foo.bar.baz

// converted to
var _tmp = foo.bar;
_tmp.baz
```
but if there is an `optional` flag it would change the meaning for

```
foo?.bar.baz

// converted to
var _tmp = foo?.bar;
_tmp.baz
```
so it may not throw an exception, but the plugin is certainly broken.

**Comment by loganfsmyth** [comment]
To be clear, I don't have my mind set on reusing `MemberEspression` or not, I'm more concerned about the tri-state of the flag being a new precedent and to me very confusing.

It seems to me like the short-circuiting behavior that this spec introduces necessitates the addition of a `ParenthesizedExpression` node, since this proposal makes paren-groupings have semantic meaning during execution. Then we could keep `optional: boolean` and rely on the presence of the paren grouping to determine the rest.

Thoughts?

**Comment by jridgewell** [comment]
`ParenthesizedExpression` could certainly be added, but I imagine many transforms will need to update to handle it.

Would a enum be better instead of a tri-state? My intuition, though, is that a new AST node is more likely to break things than a new field on an existing one. Though, it might be easier to determine, since you'd be suddenly be getting `OptionalMemberExpression` or `ParenthesizedExpression`s where you didn't previously expect them.

**Comment by nveenjain** [comment]
Ok, now i got that. Sorry for misinterpreting what breaking change could mean. I think that adding new nodes is more suitable/good solution. However all the optionalChain transforms will be needed to be re-written. Should i proceed with creating `OptionalMemberExpression` Node and close the PR which i opened for tri-state optional?

**Comment by nveenjain** [comment]
I think that we might require two kind of new nodes `OptionalMemberExpression` and `OptionalCallExpression`. 
As sample code for `OptionalExpression` can also be of format `obj?.()` or `obj.a?.b()` in this expression we will require `OptionalCallExpression` too. Thoughts?

**Comment by loganfsmyth** [comment]
As a side question before I respond, what is the expected behavior of
```
var String = null;
var result = String?.raw`bar`;
```
Is a tagged template executed? From the grammar in JS, my expectation is that the tagged template counts as part of the current execution chain, so the answer would be no. That  means if we _do_ go the route of the tri-state, we'd need a tri-state flag on the `MemberExpression` node, and also on `TaggedTemplateLiteral`, but on the template literal it couldn't be  `true` but could be `false` or `undefined` which would also be super confusing.

> `ParenthesizedExpression` could certainly be added, but I imagine many transforms will need to update to handle it.

Yeah, I'm on the fence about that. I don't think a ton of transforms hard-code every type of expression though, so as long as it passes `isExpression` checks, I bet the majority would have no problems with it.

Personally I like this because it feels in line with this proposal making them semantically important.

> Would a enum be better instead of a tri-state? My intuition, though, is that a new AST node is more likely to break things than a new field on an existing one.

If we do go the route of a tri-state, I'd definitely be more in favor of a `kind: "normal" | "optional" | "chain"` kind of thing though exact naming pending.

My concern is that by using a tri-state is that it conflates responsibility for two things that to me seem separate. 

* Is this an optional access that triggers an abrupt completion?
* Is this a boundary that optional abrupt completions can cross?

To make sure I follow your definitions, 

* `true` - This node is explicitly an optional access
* `false` - This node is not optional, but has a chain in its `object` that is not parenthesized
* `undefined` - This node is not optional and not part of a chain

The tri-state approach skips the concept of tri-state boundaries in favor of having them be implied as a flag on the access itself, which seems inelegant to me.

**Comment by nveenjain** [comment]
The way, I've implemented this on my PC is that 
```js
var result = String?.raw`bar`;
```
generates an ast as following:- 
```js
 [ Node {
          type: 'ExpressionStatement',
          start: 0,
          end: 16,
          loc:
           SourceLocation {
             start: Position { line: 1, column: 0 },
             end: Position { line: 1, column: 16 } },
          expression:
           Node {
             type: 'TaggedTemplateExpression',
             start: 0,
             end: 16,
             loc:
              SourceLocation {
                start: Position { line: 1, column: 0 },
                end: Position { line: 1, column: 16 } },
             tag:
              Node {
                type: 'OptionalMemberExpression',
                start: 0,
                end: 11,
                loc:
                 SourceLocation {
                   start: Position { line: 1, column: 0 },
                   end: Position { line: 1, column: 11 } },
                object:
                 Node {
                   type: 'Identifier',
                   start: 0,
                   end: 6,
                   loc:
                    SourceLocation {
                      start: Position { line: 1, column: 0 },
                      end: Position { line: 1, column: 6 },
                      identifierName: 'String' },
                   name: 'String' },
                property:
                 Node {
                   type: 'Identifier',
                   start: 8,
                   end: 11,
                   loc:
                    SourceLocation {
                      start: Position { line: 1, column: 8 },
                      end: Position { line: 1, column: 11 },
                      identifierName: 'raw' },
                   name: 'raw' },
                computed: false,
                optional: true },
             quasi:
              Node {
                type: 'TemplateLiteral',
                start: 11,
                end: 16,
                loc:
                 SourceLocation {
                   start: Position { line: 1, column: 11 },
                   end: Position { line: 1, column: 16 } },
                expressions: [],
                quasis:
                 [ Node {
                     type: 'TemplateElement',
                     start: 12,
                     end: 15,
                     loc:
                      SourceLocation {
                        start: Position { line: 1, column: 12 },
                        end: Position { line: 1, column: 15 } },
                     value: { raw: 'bar', cooked: 'bar' },
                     tail: true } ] } } } 
```
According to me, this should also be expected behaviour and rest implementation should rely on transforms on `OptionalMemberExpression`. Thoughts/suggestions?

**Comment by loganfsmyth** [comment]
@nveenjain Looks like you've still got a `optional: true` on there, which I'm assuming is just leftover from when it was still `type: MemberExpression` rather than `type: OptionalMemberExpression`? Otherwise that looks right to me.

Since I don't think I was super clear, my question is how do we differentiate

```
String = null;
var result = String?.raw`bar`;
```
which would end with `result === undefined`, vs

```
String = null;
var result = (String?.raw)`bar`;
```
which would throw as I understand things.

In the tri-state case, we'd need another flag on the `TaggedTemplateLiteral` to differentiate that, just like is being proposed for

```
String = null;
String?.raw.name
```
vs
```
String = null;
(String?.raw).name
```

**Comment by nveenjain** [comment]
@loganfsmyth , what i've implemented is using this interface
```js
interface OptionalMemberExpression <: MemberExpression {
  type: "OptionalMemberExpression";
  object: MemberExpression | CallExpression;
  property: Identifier | Expression;
  computed: boolean;
  optional: boolean;
}
```
That way, when we can check if we are inside `optionalChain`(acc. to proposed spec) or `OptionalExpression` (acc. to spec). For eg. if we are using `a?.b.c`
then we are in optional chain while traversing b,c but they are not optional Properties whereas a is an OptionalProperty so it's optional is set to true.

**Comment by loganfsmyth** [comment]
Ah I see, I think I was misunderstanding the behavior of `OptionalMemberExpression` a little bit. So the idea would be that any accesses in the chain would use that type too? If so then that's fair. That avoids the tri-state `optional` flag at least.

I also answered my own question about tagged templates by looking at the spec. https://github.com/tc39/proposal-optional-chaining#not-supported says tagged templates would not be allowed in chains. Not sure if the parser currently limits that, I'd have to check.

You are right that this approach would work, and as you mentioned in https://github.com/babel/babel/issues/7256#issuecomment-361006849 we'd also need `OptionalCallExpression`. I do wonder if `optional: boolean` is a good name for it though, since `optional` is already in the name of the node itself it's seems counterintuitive where `root: boolean` might be clearer for people?

Thanks for responding to my comments on this stuff @jridgewell and @nveenjain.

Alright, I don't have strong feelings for if we go the route of new node types vs a string enum. I do think a boolean/undefined tri-state would not be ideal though.

**Comment by nveenjain** [comment]
> Not sure if the parser currently limits that, I'd have to check.
Yeah, parser doesn't limit that as of now (and i didn't look carefully to `not supported` section of spec, so didn't know that they were not supported), but currently i'll be focusing on transforms and the new nodes for the time being. I will open separate issue, once this task is over, which will throw errors on such cases too. Is that cool with you or should i throw an error when one of `not supported` things occur?

>  I do wonder if `optional: boolean` is a good name for it though
You are right, will change that to `root:boolean`, that looks more intuitive.

**Comment by nveenjain** [comment]
@jridgewell , i created nodes, but when writing transforms, i am not getting OptionalMemberExpression when using inside a visitor. Don't know why.. Could you guide me, please?

**Comment by jridgewell** [comment]
> the idea would be that any accesses in the chain would use that type too? 

Yup, because the chain propagates upwards until it's broken by a parenthesis.

> tagged templates by looking at the spec.

Yup, they are disallowed. Optional is only allowed inside a `MemberExpression`'s `object` or `CallExpression`'s `callee`, unless it's broken by a parenthesis.

> where root: boolean might be clearer for people?

The issue is multiple optionals in a chain:

```js
obj?.a?.b.c
```

Where the `a` and `b` are optional access and the `c` isn't. We'd have multiple "roots" which seems weird.

**Comment by loganfsmyth** [comment]
> Yup, they are disallowed. Optional is only allowed inside a MemberExpression's object or CallExpression's callee, unless it's broken by a parenthesis.

Yeah I'm surprised that it isn't allowed, that seems like a weird requirement to me, but I'll accept it.

Fair. I'm open to other names, but it seems like `optional` isn't very clear to me.

**Comment by nveenjain** [comment]
I've updated the PR. #7288 , any suggestions/edits?
For now `optional` are added as property, which can be changed with just a few lines if decided.

**Comment by jridgewell** [comment]
Reopening until we confirm point 4.

**Comment by nveenjain** [comment]
In point 4, only `super object` point is a TO-DO, will complete it by night.
