### ISSUE TITLE
TypeScript 2.8 meta-issue

### ISSUE THREAD

**Issue by DanielRosenwasser** [babel/babel#7389]
TypeScript 2.8 will be introducing a number of syntactic additions in the type space including:

* [ ] conditional types (https://github.com/Microsoft/TypeScript/pull/21316)
* [ ] `infer` type parameter locations (https://github.com/Microsoft/TypeScript/pull/21496)
* [ ] improved control for modifiers on mapped types (https://github.com/Microsoft/TypeScript/pull/21919)

We can keep close track of the release [on here](https://github.com/Microsoft/TypeScript/wiki/Roadmap#28-march-2018).

@andy-ms @mhegazy
