### ISSUE TITLE
TypeScript 2.9 meta-issue

### ISSUE THREAD

**Issue by DanielRosenwasser** [babel/babel#7747]
TypeScript 2.9 will likely be introducing a number of syntactic additions in the type space as well as the expression space including:

* [ ] `import(...)` types (https://github.com/Microsoft/TypeScript/issues/14844)
  * Babel Tracking Issue: https://github.com/babel/babel/issues/7749
* [x] Generics on JSX Elements (https://github.com/Microsoft/TypeScript/pull/22415)
  * Babel Tracking Issue: https://github.com/babel/babel/issues/7748
* [x] Generics on Tagged Templates (https://github.com/Microsoft/TypeScript/pull/23430)
  * Babel Tracking Issue: https://github.com/babel/babel/issues/7746

We can keep close track of the 2.9 feature set [on here](https://github.com/Microsoft/TypeScript/wiki/Roadmap#29-may-2018).

@andy-ms @mhegazy @weswigham

**Comment by weswigham** [comment]
Also named type arguments are kinda sheduled for 2.9, though we don't have a design/implementation finalized yet.

**Comment by DanielRosenwasser** [comment]
Sounds like this is fixed.

**Comment by epeli** [comment]
Woo https://github.com/babel/babel/pull/9302#event-2066308848
