### ISSUE TITLE
Name change

### ISSUE THREAD

**Issue by sebmck** [babel/babel#780]
**Please do not comment in this issue with criticism/comments.**

### Stage 1 - Preparation

 - Branding
   - [x] Acquire GitHub org
   - [x] Acquire npm package name
   - [x] Register twitter account
   - [x] Update logo repo
   - [x] Buy domain
 - Internal
   - [x] Rename `acorn-6to5`
   - [x] Rename `regenerator-6to5`
   - [x] Update all internal references to new name

### Stage 2 - Migration/release

 - Branding
   - [x] Update website branding
   - [x] Update website homepage
 - Website
   - [x] Redirect `6to5.org` to new domain
   - [x] Write blog post
 - Release
   - [x] Publish new core packages
 - Update references
   - [x] [6to5ify](https://github.com/6to5/6to5ify)
   - [x] [6to5-connect](https://github.com/6to5/6to5-connect)
   - [x] [6to5-jest](https://github.com/6to5/6to5-jest)
   - [x] [6to5-library-boilerplate](https://github.com/6to5/6to5-library-boilerplate) babel/6to5-library-boilerplate#114
   - [x] [6to5-loader](https://github.com/6to5/6to5-loader)
   - [x] [6to5-sublime](https://github.com/6to5/6to5-sublime)
   - [x] [accord](https://github.com/jenius/accord/pull/68)
   - [ ] [atom](https://github.com/atom/atom/pull/5299) atom/atom#5579
   - [x] [atom-shell-starter](https://github.com/atom/atom-shell-starter/pull/35) atom/atom-shell-starter/pull/45
   - [x] [broccoli-6to5-transpiler](https://github.com/6to5/broccoli-6to5-transpiler)
   - [x] [brunch-6to5](https://github.com/6to5/6to5-brunch)
   - [x] [cogs-transformer-6to5](https://github.com/caseywebdev/cogs-transformer-6to5)
   - [x] [compat-table](https://github.com/kangax/compat-table) kangax/compat-table#439
   - [x] [grunt-6to5](https://github.com/6to5/grunt-6to5)
   - [x] [duo-6to5](https://github.com/6to5/duo-6to5)
   - [x] [ember-cli-6to5](https://github.com/6to5/ember-cli-6to5)  babel/ember-cli-6to5#14
   - [x] [ember-cli](https://github.com/ember-cli/ember-cli) ember-cli/ember-cli#3297
   - [x] [es6-module-loader](https://github.com/ModuleLoader/es6-module-loader)
   - [x] [espower-6to5](https://github.com/azu/espower-6to5)
   - [x] [estree](https://github.com/estree/estree)
   - [x] [gobble-6to5](https://github.com/6to5/gobble-6to5)
   - [x] [gulp-6to5](https://github.com/6to5/gulp-6to5)
   - [x] [isparta](https://github.com/douglasduteil/isparta)
   - [x] [jade-6to5](https://github.com/6to5/jade-6to5)
   - [x] [jspm](https://github.com/jspm/jspm-cli) jspm/jspm-cli/pull/514
   - [x] [JSXLint](https://github.com/STRML/JSXHint/pull/32)
   - [x] [karma-6to5-preprocessor](https://github.com/6to5/karma-6to5-preprocessor)
   - [x] [kraken-devtools-6to5](https://github.com/xjamundx/kraken-devtools-6to5)
   - [x] [metalsmith-6to5](https://github.com/6to5/metalsmith-6to5)
   - [x] [mimosa-6to5](https://github.com/YoloDev/mimosa-6to5)
   - [x] [rails](https://github.com/6to5/6to5-rails)
   - [x] [ruby](https://github.com/6to5/6to5-ruby) babel/ruby-6to5/issues/88

FYI @babel/everyone

**Comment by thejameskyle** [comment]
I have the blog post partially done, it should be complete in a day or so.

**Comment by es128** [comment]
What is the new name?

**Comment by sebmck** [comment]
Not willing to disclose the new name publicly because people will jump the gun and start all sorts of drama. Check out the [private org gitter room](https://gitter.im/6to5) to find out.

**Comment by es128** [comment]
Looks like I haven't been granted access there.

**Comment by sebmck** [comment]
Everyone in the org *should* have access. I might have to manually add people.

**Comment by es128** [comment]
Ok it was my bad. Wasn't logged in to gitter on my mobile. They could make that landing page a bit clearer.

**Comment by aeosynth** [comment]
> Not willing to disclose the new name publicly

the new logo appears in the readme

**Comment by sebmck** [comment]
@aeosynth Yeah because I'm an idiot.

**Comment by sebmck** [comment]
Welp anyway, the new name is babel.

![logo](https://cloud.githubusercontent.com/assets/853712/6202803/137ba04c-b552-11e4-9c81-7e17e6270a23.png)

**Comment by Dashed** [comment]
@sebmck We now need a voice recording of how you say **babel**. Then put it in FAQ, under "What's the proper way to saying babel?".

**Comment by sebmck** [comment]
I don't really care how people pronounce it as long as it's not bloody BAY-BELL.

**Comment by sebmck** [comment]
Also he's a taste of what the logo could've been...

![screen shot 2015-02-15 at 4 58 42 pm](https://cloud.githubusercontent.com/assets/853712/6203058/8c2ec976-b55f-11e4-8431-a0ef9cfeb4d4.png)

:-1:

**Comment by Dashed** [comment]
That logo feels like a New Balance logo.

**Comment by sebmck** [comment]
@stefanpenner for `ember-cli-6to5` and `ember-cli`.
@josh for `ruby-6to5` and `sprockets-es6`.
@Alxandr for `mimosa-6to5`.
@douglasduteil for `isparta`.
@guybedford for `es6-module-loader` and `jspm`.
@azu for `espower-6to5`.
@caseywebdev for `cogs-transformer-6to5`.
@jenius for `accord`.
@jmeas for `6to5-library-boilerplate`.
@xjamundx for `kraken-devtools-6to5`.
@STRML for `jsxhint`.

Thanks everyone!

**Comment by josh** [comment]
Do we have a recommendation for a new file extension instead of `.es6`?

**Comment by sebmck** [comment]
@josh Only one that comes to mind is `.jsx`.

**Comment by lukescott** [comment]
> I don't really care how people pronounce it as long as it's not bloody BAY-BELL

@sebmck Just curious, how do you say it? That's how it's said here (western USA). Also `Terminal> say babel`.

**Comment by sebmck** [comment]
@lukescott Bah-bull. Truth be told I don't really care how people pronounce it at all, I'm just being dramatic :stuck_out_tongue_winking_eye:

**Comment by fivetanley** [comment]
@sebmck I opened https://github.com/babel/ember-cli-6to5/pull/14 and https://github.com/ember-cli/ember-cli/pull/3297 for ember-cli and ember-cli-6to5

**Comment by SerkanSipahi** [comment]
i opened this https://github.com/systemjs/systemjs/issues/350 for systemjs

**Comment by jmeas** [comment]
Will update the boilerplate in a few dayz

**Comment by wyaeld** [comment]
> Do we have a recommendation for a new file extension instead of .es6?

> @josh Only one that comes to mind is .jsx

@sebmck That might cause issues with the React.js JSX transpilers, lots of people starting projects atm with React, JSX and 6to5 in together

**Comment by sebmck** [comment]
@wyaeld Babel is a builtin JSX transformer that's 100% compatible with the official Facebook one which is why I suggested it so it's not really an issue.

**Comment by xlaywan** [comment]
My suggestion is use .jsn (or .esn?) for a new file extension recommendation. Here `n` can mean Next, ES2015(n-th year) or Mozilla style JS naming like JS 1.8(n-th version).

**Comment by sebmck** [comment]
@xlaywan Extensions based on the version of a living standard is generally a bad idea.

**Comment by sebmck** [comment]
@xlaywan A new extension probably isn't a good idea. Tooling would need to adapt to it and `.jsx` is suitable anyway due to the JSX support and there's already support for it as an extension.

**Comment by Alxandr** [comment]
mimosa-babel is done.

**Comment by jenius** [comment]
accord is done. thanks for the heads up guys! :two_men_holding_hands:

**Comment by xjamundx** [comment]
https://github.com/xjamundx/kraken-devtools-babel has been migrated/renamed

**Comment by jmeas** [comment]
@sebmck done. https://github.com/babel/babel-library-boilerplate

**Comment by sebmck** [comment]
Alright I think this is good to close now, only thing that I'm waiting on is atom/atom#5579. Thanks everyone for your support and cooperation!

**Comment by arcanis** [comment]
I've just remember why this logo looked familiar. Not quite similar, but there's something ! :)

![](http://inmyotherworld.free.fr/gfx/blakemortimer/08.jpg)
